#!/bin/bash
# Audio Compression Script for Hablas Project
# Compresses speech audio to optimal 64 kbps for storage efficiency
# Generated by: QA Testing Agent
# Date: November 1, 2025

set -e

echo "======================================"
echo "Hablas Audio Compression Utility"
echo "======================================"
echo ""

# Configuration
AUDIO_DIR="public/audio"
BITRATE="64k"
SAMPLE_RATE="24000"
CHANNELS="1"

# Files requiring compression (>5MB)
FILES=(
  "resource-2.mp3"
  "resource-7.mp3"
  "resource-10.mp3"
  "resource-13.mp3"
  "resource-18.mp3"
  "resource-21.mp3"
  "resource-28.mp3"
  "resource-32.mp3"
  "resource-34.mp3"
)

# Check if ffmpeg is installed
if ! command -v ffmpeg &> /dev/null; then
    echo "ERROR: ffmpeg is not installed"
    echo "Install with: sudo apt-get install ffmpeg (Linux)"
    echo "Or: brew install ffmpeg (Mac)"
    exit 1
fi

# Navigate to audio directory
cd "$AUDIO_DIR" || exit 1
echo "Working directory: $(pwd)"
echo ""

# Calculate initial storage
INITIAL_SIZE=$(du -sh . | awk '{print $1}')
echo "Initial storage: $INITIAL_SIZE"
echo ""

# Process each file
TOTAL_FILES=${#FILES[@]}
CURRENT=0
SAVED_BYTES=0

for file in "${FILES[@]}"; do
  CURRENT=$((CURRENT + 1))

  if [ ! -f "$file" ]; then
    echo "[$CURRENT/$TOTAL_FILES] WARNING: $file not found, skipping..."
    continue
  fi

  # Get original size
  ORIGINAL_SIZE=$(stat -c%s "$file" 2>/dev/null || stat -f%z "$file")
  ORIGINAL_MB=$(echo "scale=2; $ORIGINAL_SIZE/1048576" | bc)

  echo "[$CURRENT/$TOTAL_FILES] Processing: $file"
  echo "  Original size: ${ORIGINAL_MB} MB"

  # Create backup
  BACKUP="${file}.backup"
  if [ -f "$BACKUP" ]; then
    echo "  Backup exists, skipping backup creation"
  else
    cp "$file" "$BACKUP"
    echo "  Backup created: $BACKUP"
  fi

  # Compress file
  TEMP_FILE="${file}.tmp"
  echo "  Compressing to ${BITRATE} @ ${SAMPLE_RATE}Hz..."

  ffmpeg -i "$file" \
    -b:a "$BITRATE" \
    -ar "$SAMPLE_RATE" \
    -ac "$CHANNELS" \
    -y "$TEMP_FILE" \
    -loglevel error

  # Replace original with compressed
  mv "$TEMP_FILE" "$file"

  # Calculate savings
  NEW_SIZE=$(stat -c%s "$file" 2>/dev/null || stat -f%z "$file")
  NEW_MB=$(echo "scale=2; $NEW_SIZE/1048576" | bc)
  SAVED=$(echo "$ORIGINAL_SIZE - $NEW_SIZE" | bc)
  SAVED_BYTES=$((SAVED_BYTES + SAVED))
  SAVED_MB=$(echo "scale=2; $SAVED/1048576" | bc)
  PERCENT=$(echo "scale=1; ($SAVED * 100) / $ORIGINAL_SIZE" | bc)

  echo "  New size: ${NEW_MB} MB"
  echo "  Saved: ${SAVED_MB} MB (${PERCENT}%)"
  echo "  ✓ Complete"
  echo ""
done

# Final summary
FINAL_SIZE=$(du -sh . | awk '{print $1}')
TOTAL_SAVED_MB=$(echo "scale=2; $SAVED_BYTES/1048576" | bc)

echo "======================================"
echo "Compression Complete!"
echo "======================================"
echo "Files processed: $CURRENT"
echo "Initial storage: $INITIAL_SIZE"
echo "Final storage: $FINAL_SIZE"
echo "Total saved: ${TOTAL_SAVED_MB} MB"
echo ""
echo "Backups stored as: *.backup"
echo "To restore: cp file.mp3.backup file.mp3"
echo ""
echo "Next steps:"
echo "1. Test audio playback quality"
echo "2. Verify resource mappings work"
echo "3. Delete backup files after validation"
echo "======================================"
